# phishing_streamlit_ui.py
# LLM-Assisted Narrative: Orchestrates the display of natural language summaries and contextual insights generated by the backend LLM, providing a conversational layer over the raw data.  
# Unified Client Interface: Functions as a robust MCP client that integrates analytical pipelines with a persistent conversational memory, maintaining a cohesive chat history via session state.  
# Comprehensive Tracing: Manages a complete unified view that balances displaying LLM-generated summaries, raw executed tool outputs, and deep trace logs within a single responsive layout.  

import logging
import os
import json
import time
import asyncio
import traceback
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

import requests
import streamlit as st

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
LOGGER = logging.getLogger("phishing_streamlit_ui")

# Server Configuration Environments
LLM_SERVER_URL = os.getenv("LLM_SERVER_URL", "http://127.0.0.1:8001").rstrip("/")
EXECUTION_MODE = "mcp_stdio"
MCP_SERVER_COMMAND = os.getenv("MCP_SERVER_COMMAND", "python")
MCP_SERVER_SCRIPT = os.getenv("MCP_SERVER_SCRIPT", "phishing_mcp_server.py")
REQUEST_TIMEOUT = int(os.getenv("UI_REQUEST_TIMEOUT", "120"))
APP_TITLE = "Phishing Simulation Analytics Copilot"

st.set_page_config(page_title=APP_TITLE, page_icon="🛡️", layout="wide", initial_sidebar_state="expanded")

TOOL_LABELS = {
    "run_analytics": "Historical analytics",
    "employee_lookup": "Employee lookup",
    "predict_risk": "ML prediction",
    "recommend_actions": "Recommendations",
    "simulation_users": "Simulation users",
    "cache_control": "Cache control",
    "cache_status": "Cache status",
    "system_info": "System info",
}

EXAMPLE_QUESTIONS = [
    "percentage of people clicked on January phishing mail",
    "city with most clickers",
    "department wise click rate in 2026",
    "top risky employees",
    "show profile for BRID 75b4ae75-b",
    "predict no action probability for BRID 75b4ae75-b",
    "predict for city Pune department cyber subject password reset",
    "predicted high risk users",
    "how can BRID 75b4ae75-b improve",
    "who clicked in March 2026 simulation",
    "cache status",
    "refresh cache",
    "health check",
    "show table schema",
]

st.markdown("""<style>
:root {
    --bg-main: #0B111F;
    --bg-sidebar: #07101d;
    --bg-card: #0F1B2D;
    --border: #253449;
    --border-soft: #1e2b3d;
    --text: #e5edf7;
    --muted: #9caec4;
    --accent: #2dd4bf;
}
body, .stApp, .main {
    background: #0B111F;
    color: var(--text);
}
.block-container { max-width: 1360px; padding-top: 1.4rem; padding-bottom: 2rem; }
[data-testid="stSidebar"] { background: var(--bg-sidebar); border-right: 1px solid var(--border); }
[data-testid="stSidebar"] * { color: var(--text); }
.hero-card { background: rgba(15, 27, 45, 0.95); border: 1px solid var(--border); border-radius: 16px; padding: 1.25rem; margin-bottom: 1rem; }
.main-title { font-size: 2.15rem; font-weight: 700; letter-spacing: -0.04em; margin-bottom: 0.25rem; color: #f8fafc; }
.sub-title { font-size: 0.95rem; color: var(--muted); }
.metric-card { background: rgba(15, 27, 45, 0.92); border: 1px solid var(--border-soft); border-radius: 14px; padding: 1rem; min-height: 96px; }
.metric-label { font-size: 0.75rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.04em; }
.metric-value { font-size: 1.05rem; color: #f8fafc; font-weight: 700; margin-top: 0.4rem; }
.metric-caption { font-size: 0.75rem; color: var(--muted); margin-top: 0.25rem; }
.badge { display: inline-block; padding: 0.2rem 0.6rem; border-radius: 999px; font-size: 0.75rem; border: 1px solid var(--border); background: #101d31; color: var(--muted); margin-right: 0.5rem; margin-top: 0.35rem; }
.badge-tool { border-color: rgba(45, 212, 191, 0.3); color: #2dd4bf; }
.badge-latency { border-color: rgba(96, 165, 250, 0.3); color: #60a5fa; }
.badge-ok { border-color: rgba(34, 197, 94, 0.3); color: #22c55e; }
</style>""", unsafe_allow_html=True)


def now_time() -> str:
    return datetime.now().strftime("%H:%M:%S")


def clean_json_value(value: Any) -> Any:
    try:
        if value is None:
            return None
        if isinstance(value, (str, int, float, bool)):
            return value
        if isinstance(value, dict):
            return {str(k): clean_json_value(v) for k, v in value.items()}
        if isinstance(value, (list, tuple)):
            return [clean_json_value(x) for x in value]
        return str(value)
    except Exception:
        return str(value)


def safe_json_loads(text: str) -> Dict[str, Any]:
    try:
        return json.loads(text)
    except Exception:
        return {}


def compact_preview(value: Any, limit: int = 1500) -> str:
    try:
        text = json.dumps(clean_json_value(value), default=str, ensure_ascii=False, indent=2)
    except Exception:
        text = str(value)
    return text[:limit] + "\n...truncated..." if len(text) > limit else text


def add_log(logs: List[Dict[str, Any]], step: str, message: str, data: Any = None) -> None:
    item = {"time": now_time(), "step": step, "message": message, "data": clean_json_value(data) if data is not None else None}
    logs.append(item)


def post_json(url: str, payload: Dict[str, Any], timeout: int = REQUEST_TIMEOUT) -> Dict[str, Any]:
    LOGGER.info("POST_JSON | url=%s | payload_keys=%s", url, list(payload.keys()))
    response = requests.post(url, json=payload, timeout=timeout)
    response.raise_for_status()
    result = clean_json_value(response.json())
    LOGGER.info("POST_JSON_RESPONSE | url=%s | status_code=%s", url, response.status_code)
    return result


def get_json(url: str, timeout: int = 20) -> Dict[str, Any]:
    LOGGER.info("GET_JSON | url=%s", url)
    response = requests.get(url, timeout=timeout)
    response.raise_for_status()
    result = clean_json_value(response.json())
    LOGGER.info("GET_JSON_RESPONSE | url=%s | status_code=%s", url, response.status_code)
    return result


def check_llm_server() -> Tuple[bool, Dict[str, Any]]:
    try:
        return True, get_json(f"{LLM_SERVER_URL}/health", timeout=5)
    except Exception as e:
        return False, {"status": "error", "message": str(e)}


def select_tool(question: str, user_role: str, previous_tools: List[str], logs: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    LOGGER.info("SELECT_TOOL | question=%s | user_role=%s | previous_tools=%s", question, user_role, previous_tools)
    logs = logs if logs is not None else []
    payload = {
        "question": question,
        "user_role": user_role,
        "top_k": 3,
        "similarity_threshold": 0.35,
        "previous_selected_tools": previous_tools,
    }
    add_log(logs, "LLM_SELECT_REQUEST", "Calling LLM server /select_tool_batch", payload)
    result = post_json(f"{LLM_SERVER_URL}/select_tool_batch", payload)
    add_log(logs, "LLM_SELECT_RESPONSE", "Received tool selection response", result)
    LOGGER.info("SELECT_TOOL_RESPONSE | selected_tools=%s", [tool.get("tool_name") for tool in result.get("selected_tools", [])])
    return result


def summarize_answer(question: str, tool_name: str, tool_args: Dict[str, Any], tool_output: Dict[str, Any], user_role: str, logs: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    LOGGER.info("SUMMARIZE_ANSWER | question=%s | tool_name=%s", question, tool_name)
    logs = logs if logs is not None else []
    payload = {
        "question": question,
        "tool_name": tool_name,
        "tool_args": tool_args or {},
        "tool_output": tool_output or {},
        "user_role": user_role,
    }
    add_log(logs, "LLM_SUMMARY_REQUEST", "Calling LLM server /summarize explanation layer", payload)
    result = post_json(f"{LLM_SERVER_URL}/summarize", payload)
    add_log(logs, "LLM_SUMMARY_RESPONSE", "LLM summary response received", result)
    LOGGER.info("SUMMARIZE_ANSWER_RESPONSE | tool_name=%s | status=%s", tool_name, result.get("status"))
    return result


def fallback_final_answer(tool_name: str, tool_output: Dict[str, Any]) -> str:
    if not isinstance(tool_output, dict):
        return "Tool completed but returned unexpected output."

    if "ui_summary" in tool_output:
        return tool_output["ui_summary"]

    status = tool_output.get("status", "unknown")
    if status == "error":
        return f"The tool returned an error: {tool_output.get('message', 'Unknown error')}"

    return f"{TOOL_LABELS.get(tool_name, tool_name)} completed with status: {status}."


async def execute_tool_mcp_stdio_async(tool_name: str, tool_args: Dict[str, Any], logs: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    logs = logs if logs is not None else []
    try:
        from mcp import ClientSession, StdioServerParameters
        from mcp.client.stdio import stdio_client

        add_log(logs, "MCP_STDIO_START", "Starting MCP stdio server", {"command": MCP_SERVER_COMMAND, "script": MCP_SERVER_SCRIPT, "tool": tool_name, "args": tool_args})
        server_params = StdioServerParameters(command=MCP_SERVER_COMMAND, args=[MCP_SERVER_SCRIPT])
        async with stdio_client(server_params) as (read, write):
            async with ClientSession(read, write) as session:
                add_log(logs, "MCP_INITIALIZE", "Initializing MCP session")
                await session.initialize()
                add_log(logs, "MCP_TOOL_START", f"Calling MCP tool: {tool_name}", tool_args)
                started = time.time()
                result = await session.call_tool(tool_name, arguments=tool_args or {})
                latency = round((time.time() - started) * 1000, 2)
                add_log(logs, "MCP_TOOL_RAW_RESULT", f"MCP tool returned in {latency} ms", clean_json_value(result.model_dump() if hasattr(result, "model_dump") else result))
                if hasattr(result, "content") and result.content:
                    first = result.content[0]
                    text = getattr(first, "text", None)
                    if text:
                        parsed = safe_json_loads(text)
                        final = parsed if parsed else {"status": "success", "raw_text": text}
                        add_log(logs, "MCP_TOOL_PARSED_RESULT", "Parsed MCP tool response", final)
                        return clean_json_value(final)
                return clean_json_value(result.model_dump() if hasattr(result, "model_dump") else result)
    except Exception as e:
        err_payload = {"status": "error", "message": str(e), "traceback": traceback.format_exc()}
        add_log(logs, "MCP_STDIO_EXCEPTION", "MCP stdio execution failed", err_payload)
        return err_payload


def execute_selected_tool(tool_name: str, tool_args: Dict[str, Any], logs: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    logs = logs if logs is not None else []
    add_log(logs, "EXECUTION_MODE", f"Enforced execution mode: {EXECUTION_MODE}")
    if EXECUTION_MODE != "mcp_stdio":
        return {"status": "error", "message": "Direct execution mode is disabled in this UI."}
    return asyncio.run(execute_tool_mcp_stdio_async(tool_name, tool_args, logs))

async def execute_selected_tool_async(tool_name: str, tool_args: Dict[str, Any], logs: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    logs = logs if logs is not None else []
    if EXECUTION_MODE != "mcp_stdio":
        add_log(logs, "EXECUTION_WARNING", "Direct execution mode is disabled. Mocking failure.")
        return {"status": "error", "message": "Direct execution mode is disabled in this UI."}
    return await execute_tool_mcp_stdio_async(tool_name, tool_args, logs)

async def execute_selected_tools_async(selected_tools: List[Dict[str, Any]], logs: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    logs = logs if logs is not None else []

    async def run_tool(tool: Dict[str, Any]) -> Tuple[str, Any]:
        tool_name = tool.get("tool_name")
        tool_args = tool.get("args", {})
        add_log(logs, "TOOL_TASK_STARTED", f"Scheduling tool: {tool_name}", tool_args)
        try:
            output = await execute_selected_tool_async(tool_name, tool_args, logs)
            return tool_name, output
        except Exception as exc:
            err_payload = {"status": "error", "message": str(exc), "traceback": traceback.format_exc()}
            add_log(logs, "TOOL_TASK_FAILED", f"Tool {tool_name} failed", err_payload)
            return tool_name, err_payload

    tasks = [asyncio.create_task(run_tool(tool)) for tool in selected_tools]
    results = await asyncio.gather(*tasks, return_exceptions=False)
    return {tool_name: output for tool_name, output in results}


def run_full_pipeline(question: str, user_role: str, previous_tools: List[str]) -> Dict[str, Any]:
    LOGGER.info("RUN_FULL_PIPELINE | question=%s | user_role=%s", question, user_role)
    started = time.time()
    logs: List[Dict[str, Any]] = []
    add_log(logs, "PIPELINE_START", "Starting batch analysis pipeline", {"question": question, "user_role": user_role})

    selected = select_tool(question, user_role, previous_tools, logs)
    if selected.get("status") == "error":
        return {
            "status": "validation_error",
            "final_answer": selected.get("validation_error", "Validation Error"),
            "selected_tools": [],
            "tool_outputs": {},
            "selection": selected,
            "logs": logs,
            "latency_ms": round((time.time() - started) * 1000, 2),
        }

    selected_tools = selected.get("selected_tools", [])
    if not selected_tools:
        return {
            "status": "error",
            "final_answer": "No tools were selected by the routing engine.",
            "selected_tools": [],
            "tool_outputs": {},
            "selection": selected,
            "logs": logs,
            "latency_ms": round((time.time() - started) * 1000, 2),
        }

    add_log(logs, "BATCH_EXECUTION", "Starting concurrent tool execution")
    tool_outputs = asyncio.run(execute_selected_tools_async(selected_tools, logs))

    summaries: Dict[str, Any] = {}
    final_answers: List[str] = []
    has_error = False

    for tool in selected_tools:
        tool_name = tool.get("tool_name")
        tool_args = tool.get("args", {})
        output = tool_outputs.get(tool_name, {"status": "error", "message": "Tool did not return output"})

        if isinstance(output, dict) and output.get("status") == "error":
            has_error = True

        try:
            summary = summarize_answer(question, tool_name, tool_args, output, user_role, logs)
            ans = summary.get("final_answer") or fallback_final_answer(tool_name, output)
        except Exception:
            ans = fallback_final_answer(tool_name, output)
            summary = {"status": "fallback"}

        summaries[tool_name] = summary
        final_answers.append(f"**{TOOL_LABELS.get(tool_name, tool_name)}:**\n{ans}")

    latency_ms = round((time.time() - started) * 1000, 2)
    status = "error" if has_error else "success"
    combined_final_answer = "\n\n---\n\n".join(final_answers)

    add_log(logs, "PIPELINE_END", "Batch pipeline completed", {"status": status, "latency_ms": latency_ms})
    return {
        "status": status,
        "final_answer": combined_final_answer,
        "selected_tools": selected_tools,
        "tool_outputs": tool_outputs,
        "selection": selected,
        "summaries": summaries,
        "logs": logs,
        "latency_ms": latency_ms,
    }


def init_state() -> None:
    defaults = {
        "messages": [],
        "user_role": os.getenv("DEFAULT_USER_ROLE", "user"),
        "show_debug": True,
        "pending_question": "",
    }
    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


def render_sidebar() -> None:
    with st.sidebar:
        st.markdown("### Control Panel")
        st.selectbox("Access mode", ["user", "admin"], key="user_role")
        st.session_state.show_debug = st.toggle("Show trace below answers", value=st.session_state.show_debug)

        st.markdown("---")
        ok, health = check_llm_server()
        if ok:
            st.success("Routing engine online")
        else:
            st.error("Routing engine not reachable")
        with st.expander("Server health", expanded=False):
            st.json(health)

        st.caption(f"LLM Server: `{LLM_SERVER_URL}`")
        st.caption(f"Execution mode: `{EXECUTION_MODE}`")

        st.markdown("---")
        c1, c2 = st.columns(2)
        with c1:
            if st.button("Clear chat", use_container_width=True):
                st.session_state.messages = []
                st.session_state.pending_question = ""
                st.rerun()
        with c2:
            if st.button("Cache status", use_container_width=True):
                st.session_state.pending_question = "cache status"
                st.rerun()
        if st.button("Refresh cache", use_container_width=True):
            st.session_state.pending_question = "refresh cache"
            st.rerun()

        st.markdown("---")
        st.markdown("### Quick prompts")
        for idx, item in enumerate(EXAMPLE_QUESTIONS):
            if st.button(item, key=f"example_{idx}", use_container_width=True):
                st.session_state.pending_question = item
                st.rerun()


def render_header() -> None:
    st.markdown(
        f"""
        <div class="hero-card">
            <div class="main-title">{APP_TITLE}</div>
            <div class="sub-title">Cache-first analytics • semantic tool routing • isolated MCP runtime</div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(
            f"<div class='metric-card'><div class='metric-label'>Execution</div><div class='metric-value'>{EXECUTION_MODE.upper()}</div><div class='metric-caption'>Isolated backend transport</div></div>",
            unsafe_allow_html=True,
        )
    with c2:
        st.markdown(
            f"<div class='metric-card'><div class='metric-label'>Routing</div><div class='metric-value'>LLM Server</div><div class='metric-caption'>Semantic tool selection</div></div>",
            unsafe_allow_html=True,
        )
    with c3:
        st.markdown(
            f"<div class='metric-card'><div class='metric-label'>Role</div><div class='metric-value'>{st.session_state.user_role.upper()}</div><div class='metric-caption'>Visibility enforcement</div></div>",
            unsafe_allow_html=True,
        )


def render_trace_drawer(backend: Dict[str, Any]) -> None:
    if not backend or not st.session_state.show_debug:
        return

    tools = backend.get("selected_tools", [])
    tool_names = ", ".join([t.get("tool_name", "Unknown") for t in tools]) if tools else "None"

    st.markdown(
        f"""
        <div style='margin-top: 10px; margin-bottom: 10px;'>
            <span class='badge badge-tool'>Tools: {tool_names}</span>
            <span class='badge badge-latency'>Latency: {backend.get('latency_ms', 0)} ms</span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    with st.expander("🔎 View execution trace", expanded=False):
        t1, t2, t3, t4 = st.tabs(["Selection", "Tools & Args", "Tool Outputs", "Logs"])
        with t1:
            st.json(backend.get("selection") or {})
        with t2:
            st.json(backend.get("selected_tools") or {})
        with t3:
            st.json(backend.get("tool_outputs") or {})
        with t4:
            logs = backend.get("logs") or []
            if not logs:
                st.info("No internal logs available.")
            for log in logs:
                st.markdown(f"**{log.get('time')}** — {log.get('step')}: {log.get('message')}")
                if log.get("data") is not None:
                    st.caption(compact_preview(log.get("data"), limit=400))


def render_chat() -> None:
    if not st.session_state.messages:
        st.info("Ask a question below or choose a quick prompt from the sidebar.")
        return

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.write(msg["content"])
            if msg["role"] == "assistant" and isinstance(msg.get("backend"), dict):
                backend = msg["backend"]
                tool_outputs = backend.get("tool_outputs", {})
                if tool_outputs:
                    st.markdown("---")
                    st.markdown("### 📊 Analytics Data")
                    for t_name, t_out in tool_outputs.items():
                        ui_highlights = t_out.get("ui_highlights", []) if isinstance(t_out, dict) else []
                        if ui_highlights:
                            st.markdown(f"**{TOOL_LABELS.get(t_name, t_name)} Metrics:**")
                            cols = st.columns(min(len(ui_highlights), 4))
                            for i, highlight in enumerate(ui_highlights):
                                label = highlight.get("label", "")
                                value = highlight.get("value", "")
                                cols[i % 4].metric(label=label, value=value)
                            st.write("")

                        with st.expander(f"Raw Output: {TOOL_LABELS.get(t_name, t_name)}"):
                            st.json(t_out)
                render_trace_drawer(backend)


def handle_question(question: str) -> None:
    question = str(question or "").strip()
    if not question:
        return

    LOGGER.info("HANDLE_QUESTION | question=%s", question)
    st.session_state.messages.append({"role": "user", "content": question, "time": now_time()})

    previous_tools = []
    for message in st.session_state.messages:
        if message.get("role") == "assistant" and isinstance(message.get("backend"), dict):
            backend = message["backend"]
            if backend.get("selected_tool"):
                previous_tools.append(backend["selected_tool"])
            for tool in backend.get("selected_tools", []):
                if tool.get("tool_name"):
                    previous_tools.append(tool.get("tool_name"))

    with st.spinner("Executing workflow..."):
        result = run_full_pipeline(question, st.session_state.user_role, previous_tools)

    LOGGER.info("HANDLE_QUESTION_RESULT | question=%s | status=%s", question, result.get("status"))
    st.session_state.messages.append({
        "role": "assistant",
        "content": result.get("final_answer", "The workflow completed without producing a final answer."),
        "time": now_time(),
        "backend": result,
    })


def main() -> None:
    init_state()
    render_sidebar()
    render_header()

    if st.session_state.pending_question:
        pending = st.session_state.pending_question
        st.session_state.pending_question = ""
        handle_question(pending)
        st.rerun()

    render_chat()
    prompt = st.chat_input("Ask about phishing analytics, recommendations, predictions, or cache status...")
    if prompt:
        handle_question(prompt)
        st.rerun()


if __name__ == "__main__":
    main()


# streamlit run phishing_streamlit_ui.py